version: '3'
services:
  novnc:
    build: ./novnc
    container_name: novnc
    environment:
      - DISPLAY_WIDTH=800
      - DISPLAY_HEIGHT=600
    ports:
      - "9876:9876"
    networks:
      - novnc
networks:
  novnc:
